import 'package:flutter/material.dart';
import 'question.dart';
import 'package:easy_localization/easy_localization.dart';

class Questions with ChangeNotifier {
  List<Question> _items = [
    Question(
        'q1'.tr(),
        'q1a1'.tr(),
        false,
        'q1a2'.tr(),
        true,
        'q1a3'.tr(),
        false,
        'q1a4'.tr(),
        false,
        List.from([
          'pda1_1'.tr(),
          'pda1_2'.tr(),
          'pda1_3'.tr(),
          'pda1_4'.tr(),
          'pda1_5'.tr()
        ]),
        'assets/images/q1image.jpg',
        'assets/images/pda1image.gif'),

    Question(
        'q2'.tr(),
        'q2a1'.tr(),
        false,
        'q2a2'.tr(),
        false,
        'q2a3'.tr(),
        true,
        'q2a4'.tr(),
        false,
        List.from([
          'pda2_1'.tr(),
          'pda2_2'.tr(),
          'pda2_3'.tr()
        ]),
        'assets/images/q2image.jpg',
        'assets/images/pda2image.gif'),

    Question(
        'q3'.tr(),
        'q3a1'.tr(),
        false,
        'q3a2'.tr(),
        false,
        'q3a3'.tr(),
        true,
        'q3a4'.tr(),
        false,
        List.from([
          'pda3_1'.tr(),
          'pda3_2'.tr(),
          'pda3_3'.tr()
        ]),
        'assets/images/q3image.jpg',
        'assets/images/pda3image.gif'),

    Question(
        'q4'.tr(),
        'q4a1'.tr(),
        true,
        'q4a2'.tr(),
        false,
        'q4a3'.tr(),
        false,
        'q4a4'.tr(),
        false,
        List.from([
          'pda4_1'.tr(),
          'pda4_2'.tr(),
          'pda4_3'.tr(),
          'pda4_4'.tr(),
          'pda4_5'.tr()
        ]),
        'assets/images/q4image.jpg',
        'assets/images/pda4image.gif'),

    Question(
        'q5'.tr(),
        'q5a1'.tr(),
        true,
        'q5a2'.tr(),
        false,
        'q5a3'.tr(),
        false,
        'q5a4'.tr(),
        false,
        List.from([
          'pda5_1'.tr(),
          'pda5_2'.tr(),
          'pda5_3'.tr(),
          'pda5_4'.tr()
        ]),
        'assets/images/q5image.jpg',
        'assets/images/pda5image.gif'),

    Question(
        'q6'.tr(),
        'q6a1'.tr(),
        false,
        'q6a2'.tr(),
        false,
        'q6a3'.tr(),
        true,
        'q6a4'.tr(),
        false,
        List.from([
          'pda6_1'.tr(),
          'pda6_2'.tr(),
          'pda6_3'.tr(),
          'pda6_4'.tr(),
          'pda6_5'.tr()
        ]),
        'assets/images/q6image.jpg',
        'assets/images/pda6image.gif'),

    Question(
        'q7'.tr(),
        'q7a1'.tr(),
        false,
        'q7a2'.tr(),
        false,
        'q7a3'.tr(),
        false,
        'q7a4'.tr(),
        true,
        List.from([
          'pda7_1'.tr(),
          'pda7_2'.tr(),
          'pda7_3'.tr(),
          'pda7_4'.tr()
        ]),
        'assets/images/q7image.jpg',
        'assets/images/pda7image.gif'),

    Question(
        'q8'.tr(),
        'q8a1'.tr(),
        false,
        'q8a2'.tr(),
        true,
        'q8a3'.tr(),
        false,
        'q8a4'.tr(),
        false,
        List.from([
          'pda8_1'.tr(),
          'pda8_2'.tr(),
          'pda8_3'.tr(),
          'pda8_4'.tr()
        ]),
        'assets/images/q8image.jpg',
        'assets/images/pda8image.gif'),

    Question(
        'q9'.tr(),
        'q9a1'.tr(),
        false,
        'q9a2'.tr(),
        false,
        'q9a3'.tr(),
        true,
        'q9a4'.tr(),
        false,
        List.from([
          'pda9_1'.tr(),
          'pda9_2'.tr(),
          'pda9_3'.tr()
        ]),
        'assets/images/q9image.jpg',
        'assets/images/pda9image.gif'),

    Question(
        'q10'.tr(),
        'q10a1'.tr(),
        true,
        'q10a2'.tr(),
        false,
        'q10a3'.tr(),
        false,
        'q10a4'.tr(),
        false,
        List.from([
          'pda10_1'.tr(),
          'pda10_2'.tr(),
          'pda10_3'.tr(),
          'pda10_4'.tr(),
          'pda10_5'.tr()
        ]),
        'assets/images/q10image.jpg',
        'assets/images/pda10image.gif'),

    Question(
        'q11'.tr(),
        'q11a1'.tr(),
        false,
        'q11a2'.tr(),
        false,
        'q11a3'.tr(),
        true,
        'q11a4'.tr(),
        false,
        List.from([
          'pda11_1'.tr(),
          'pda11_2'.tr(),
          'pda11_3'.tr(),
          'pda11_4'.tr()
        ]),
        'assets/images/q11image.jpg',
        'assets/images/pda11image.gif'),

    Question(
        'q12'.tr(),
        'q12a1'.tr(),
        true,
        'q12a2'.tr(),
        false,
        'q12a3'.tr(),
        false,
        'q12a4'.tr(),
        false,
        List.from([
          'pda12_1'.tr(),
          'pda12_2'.tr(),
          'pda12_3'.tr()
        ]),
        'assets/images/q12image.png',
        'assets/images/pda12image.gif'),

    Question(
        'q13'.tr(),
        'q13a1'.tr(),
        false,
        'q13a2'.tr(),
        true,
        'q13a3'.tr(),
        false,
        'q13a4'.tr(),
        false,
        List.from([
          'pda13_1'.tr(),
          'pda13_2'.tr(),
          'pda13_3'.tr()
        ]),
        'assets/images/q13image.jpg',
        'assets/images/pda13image.gif'),

    Question(
        'q14'.tr(),
        'q14a1'.tr(),
        false,
        'q14a2'.tr(),
        false,
        'q14a3'.tr(),
        true,
        'q14a4'.tr(),
        false,
        List.from([
          'pda14_1'.tr(),
          'pda14_2'.tr()
        ]),
        'assets/images/q14image.jpg',
        'assets/images/pda14image.gif'),

    Question(
        'q15'.tr(),
        'q15a1'.tr(),
        false,
        'q15a2'.tr(),
        false,
        'q15a3'.tr(),
        true,
        'q15a4'.tr(),
        false,
        List.from([
          'pda15_1'.tr(),
          'pda15_2'.tr(),
          'pda15_3'.tr()
        ]),
        'assets/images/q15image.jpg',
        'assets/images/pda15image.gif'),

    Question(
        'q16'.tr(),
        'q16a1'.tr(),
        false,
        'q16a2'.tr(),
        false,
        'q16a3'.tr(),
        true,
        'q16a4'.tr(),
        false,
        List.from([
          'pda16_1'.tr(),
          'pda16_2'.tr(),
          'pda16_3'.tr(),
          'pda16_4'.tr()
        ]),
        'assets/images/q16image.jpg',
        'assets/images/pda16image.gif'),

    Question(
        'q17'.tr(),
        'q17a1'.tr(),
        true,
        'q17a2'.tr(),
        false,
        'q17a3'.tr(),
        false,
        'q17a4'.tr(),
        false,
        List.from([
          'pda17_1'.tr(),
          'pda17_2'.tr()
        ]),
        'assets/images/q17image.jpg',
        'assets/images/pda17image.gif'),

    Question(
        'q18'.tr(),
        'q18a1'.tr(),
        false,
        'q18a2'.tr(),
        true,
        'q18a3'.tr(),
        false,
        'q18a4'.tr(),
        false,
        List.from([
          'pda18_1'.tr(),
          'pda18_2'.tr(),
          'pda18_3'.tr()
        ]),
        'assets/images/q18image.jpg',
        'assets/images/pda18image.gif'),

    Question(
        'q19'.tr(),
        'q19a1'.tr(),
        false,
        'q19a2'.tr(),
        false,
        'q19a3'.tr(),
        false,
        'q19a4'.tr(),
        true,
        List.from([
          'pda19_1'.tr(),
          'pda19_2'.tr()
        ]),
        'assets/images/q19image.jpg',
        'assets/images/pda19image.gif'),

    Question(
        'q20'.tr(),
        'q20a1'.tr(),
        false,
        'q20a2'.tr(),
        false,
        'q20a3'.tr(),
        true,
        'q20a4'.tr(),
        false,
        List.from([
          'pda20_1'.tr(),
          'pda20_2'.tr(),
          'pda20_3'.tr(),
          'pda20_4'.tr()
        ]),
        'assets/images/q20image.jpg',
        'assets/images/pda20image.gif'),
  ];

  List<Question> get items{
    return[..._items];

  }

}
